### ISSUE TITLE
Annotation scanning, injection and PostConstruct/PreDestroy problem on weblogic due to refactored AnnotationScanning

### ISSUE THREAD

**Issue by javaserverfaces** [javaee/mojarra#1904]
With the changes related to [http://java.net/jira/browse/JAVASERVERFACES-1835](http://java.net/jira/browse/JAVASERVERFACES-1835) running on Weblogic server when not installing com.bea.faces.WeblogicInjectionProvider, none of the managed beans configured using @ManagedBean annotations are installed.

After adding WebligicInjectionprovider copied from shared library for JSF 1.2 - the AnnotationScanning works again since it will use JavaClassScanningAnnotationScanner as com.bea.faces.WeblogicInjectionProvider does not implement AnnotationScanner interface. But now no PostConstruct/PreDestroy annotated methods are called. That I think is a problem of com.bea.faces.WeblogicInjectionProvider - but it's delegating to WebComponentCreator.inject(..) which i did not further investigate.

Before the change for [http://java.net/jira/browse/JAVASERVERFACES-1835](http://java.net/jira/browse/JAVASERVERFACES-1835), com.sun.faces.vendor.WebContainerInjectionProvider did not implement AnnotationScanner interface and Annotation scanning and invocation of PostConstruct/PreDestroy worked well on Weblogic without installing com.bea.faces.WeblogicInjectionProvider.

Is there a way Oracle provides a com.bea.faces.WeblogicInjectionProvider to work with JSF 2.1.0 too?
Or how are we supposed to get that working on Weblogic?

After I changed WebContainerInjectionProvider (for my custom build) to not implement AnnotationScanner annotation scanning and PostConstruct/PreDestroy worked well again in Weblogic.
#### Environment
Weblogic server 10.3b
